name: 'ServiceNow DevOps Register Artifact'
description: 'Send Artifat Details to ServiceNow Devops'
inputs:
  devops-integration-user-name:
    description: 'Devops Integration User Name'
    required: false
  devops-integration-user-password:
    description: 'Devops Integration User Password'
    required: false
  instance-url: 
    description: 'ServiceNow Instance URL'
    required: true
  tool-id:
    description: 'Orchestration Tool Id'
    required: true
  job-name:
    description: 'Display Name of the Job'
    required: true
  context-github:
    description: 'Github Context'
    required: true
  artifacts:
    description: 'List of Artifacts to be registered'
    required: true
  devops-token:
    description: 'Token to authorize REST API'
    required: false
branding:
  icon: 'refresh-ccw'
  color: 'green'
runs: 
  using: 'node12'
  main: 'dist/index.js'
